# Generated by Django 3.0.6 on 2020-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='author',
            field=models.CharField(default='Godwin Laureto', max_length=30),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='content',
            field=models.TextField(default='This is a sample text.'),
        ),
    ]
